//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace $safeprojectname$
{
    using System;
    using System.Collections.Generic;
    
    public partial class Livestock
    {
        public int LSID { get; set; }
        public string Type { get; set; }
        public string Breed { get; set; }
        public Nullable<int> Total { get; set; }
    }
}
